### ISSUE TITLE
error with user_id=0

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#194]
I tried the current autoupdate service and the new client:
```
autoupdate_1        | 2021/04/15 13:30:52 Internal Error: getting keys: get all keys: create keys for keysbuilder: load needed keys: restrict data: checker for key organisation/1/committee_ids: check fqids: restrict for collection committee: checking committee/1/id: getting organisation level: getting data from datastore: getOrSet for keys `[user/0/organisation_management_level]`: fetching key: fetching missing keys: requiesting keys from datastore: datastore returned status 400 BAD REQUEST: {
autoupdate_1        |   "error": {
autoupdate_1        |     "msg": "The key 'user/0/organisation_management_level' is no fqid, fqfield or collectionkey", 
autoupdate_1        |     "type": 1, 
autoupdate_1        |     "type_verbose": "INVALID_FORMAT"
autoupdate_1        |   }
autoupdate_1        | }
```
It seems that this is the request (altough I'm not sure):
```
{"collection":"organisation","ids":[1],"fields":{"id":null,"committee_ids":{"type":"relation-list","collection":"committee","fields":{"name":null,"description":null,"id":null,"meeting_ids":{"type":"relation-list","collection":"meeting","fields":{"name":null,"start_time":null,"end_time":null,"user_ids":null,"location":null,"id":null}}}}}}
```
Not that I'm not logged in, which would explain the user id 0.

**Comment by ostcar** [comment]
This bug is kind of funny. We (datasote <-> autoupdate/permission) have to talk about the error cases.

I treat the key `user/0/organisation_management_level` as a valid key that does not exist. For keys, that do not exist, we defined, that the datastore should return `null`. The datastore seems to say, that the key is invalid.

The problem is, that I can not write a test for this situation. If I create a test with `user_id == 0`, then my datastore-mock returns `null` and I don't get the error.

Do we have an official and documented definition what a valid fqfield is? Could we create one? Afterwards, I change my test-code to return a 400er for invalid fqfields.

Proposal:

COLLECTION = [a-z][a-z0-9_]*
ID = [1-9][0-9]*
FIELD = [a-z][a-z0-9_$]*
FQID = COLLECTION + "/" + ID
FQFIELD = FQID + "/" + FIELD

**Comment by FinnStutzenstein** [comment]
We do have it: https://github.com/OpenSlides/OpenSlides/wiki/Models (originating from https://github.com/OpenSlides/OpenSlides/wiki/DE%3AKonzept-OpenSlides-4#19-einheitliche-namensgebung which we discussed in the meeting in 2020). 0 is an invalid id, so the datastore complains.

**Comment by ostcar** [comment]
Thank you. I was only looking in the /docs folder. Is there a documentation where to look for documentation? 😅

**Comment by FinnStutzenstein** [comment]
:D

The goal is to have it all in the wiki, which is rather full in comparison a year ago. Yes, the docs folder (especially the interfaces) must still be migrated and the docs folder renamed, since there are no docs than.

**Comment by GabrielInTheWorld** [comment]
Please fix this, so guests/anonymous users can sign in.
If I try to sign in with user-id 0, I get the following error:
```
2021/04/21 10:11:13 Internal Error: authenticate request: reading token: validating auth token: token is malformed: failed to unmarshal token claims
```

**Comment by ostcar** [comment]
What do you mean that you try to login with user id 0? In my understanding the anonymous user id defined as a user that is not logged in

**Comment by ostcar** [comment]
@GabrielInTheWorld the commit fixed the issue from Finn. Please check if your issue is also fixed. If not, then please open a new issue.
