### ISSUE TITLE
How to request recursively dependencies?

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#219]
There are some tree-like structures in the client. How can a client request dynamically such tree-like data?

**Comment by ostcar** [comment]
Currently, there is no way to do this in our query language. I think the best thing to solve this is to "flatten the tree". See this anwser here for graphQL which is similar to our language: https://stackoverflow.com/a/52220475

I don't think, that there is any other way. @FinnStutzenstein do you have another idea?

@GabrielInTheWorld does this answer your question?

**Comment by FinnStutzenstein** [comment]
No, you have to query them flat. E.g. the agenda: Just fetch `meeting/agenda_item_ids`. Or for the category tree fetch all categories.

The rationale behind it is that the OS3 client already had the ability to convert flat lists into trees since in OS3 we also only got the models. Currently, fur all trees it should be possible to have a relation to cover all elements in the tree. Even for the motion forwarding tree there is a calculated field `forwarding_tree_motion_ids` that serves as a link to all motions in the tree to fetch them all together.

**Comment by GabrielInTheWorld** [comment]
> No, you have to query them flat. E.g. the agenda: Just fetch `meeting/agenda_item_ids`. Or for the category tree fetch all categories.
> 

Alright, thanks!
