### ISSUE TITLE
Weird bug when requesting logos and fonts

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#382]
I sent this request to the AU-service:
```js
{
    "collection": "meeting",
    "ids": [
        5
    ],
    "fields": {
        // [...]
        "id": null,
        "logo_$_id": {
            "type": "template"
        },
        "font_$_id": {
            "type": "template"
        },
        // [...]
    }
}
```

```js
{
    "collection": "meeting",
    "ids": [
        5
    ],
    "fields": {
        "description": null,
        "name": null,
        "start_time": null,
        "end_time": null,
        "is_active_in_organization_id": null,
        "id": null,
        "mediafile_ids": {
            "type": "relation-list",
            "collection": "mediafile",
            "fields": {
                "title": null,
                "is_directory": null,
                "parent_id": null,
                "child_ids": null,
                "mimetype": null,
                "filesize": null,
                "create_timestamp": null,
                "has_inherited_access_groups": null,
                "pdf_information": null,
                "id": null,
                "used_as_font_$_in_meeting_id": {
                    "type": "template"
                },
                "used_as_logo_$_in_meeting_id": {
                    "type": "template"
                },
                // [...]
            }
        },
        // [...]
    }
}
```

I got this update:
```js
{
    "meeting/5/logo_$_id": [
        "web_header"
    ],
    "meeting/5/logo_$web_header_id": 97
}
```

```js
{
    "mediafile/97/used_as_logo_$_in_meeting_id": [
        "web_header"
    ],
    "mediafile/97/used_as_logo_$web_header_in_meeting_id": 5
}
```

Everything fine.

Then, I remove the logo as web_header and got this update:
```js
{
    "meeting/5/logo_$_id": []
}
```

```js
{
    "mediafile/97/used_as_logo_$_in_meeting_id": []
}
```

Still everything fine.

However, if I set the logo `97` as web_header, again, I got only this update:
```js
{
    "meeting/5/logo_$_id": [
        "web_header"
    ]
}
```

```js
{
    "mediafile/97/used_as_logo_$_in_meeting_id": [
        "web_header"
    ]
}
```

As you can see, there is something missing. The request doesn't changed.

Logs of the datastore-writer:
```
docker-datastore-writer-1  | 2021-12-10T12:59:54.809: [/app/datastore/writer/postgresql_backend/sql_database_backend_service.py] [INFO] Created position 156
docker-datastore-writer-1  | 2021-12-10T12:59:54.824: [/app/datastore/writer/redis_backend/redis_messaging_backend_service.py] [DEBUG] written fqfields into ModifiedFields: {"mediafile/97/used_as_logo_$web_header_in_meeting_id": "5", "mediafile/97/used_as_logo_$_in_meeting_id": "[\"web_header\"]", "mediafile/97/meta_position": "156", "meeting/5/logo_$_id": "[\"web_header\"]", "meeting/5/logo_$web_header_id": "97", "meeting/5/meta_position": "156"}
docker-datastore-writer-1  | 2021-12-10T12:59:54.825: [/app/datastore/writer/core/writer_service.py] [INFO] Events executed (3 UPDATE)
docker-datastore-writer-1  | 2021-12-10T12:59:54.825: [/app/datastore/writer/core/writer_service.py] [INFO] UPDATE: ['mediafile/97', 'meeting/5']
docker-datastore-writer-1  | 172.19.0.11 - - [10/Dec/2021 12:59:54] "POST /internal/datastore/writer/write HTTP/1.1" 201 -
```

**Comment by ostcar** [comment]
This is the expected behavior (but of case we can talk about if we should change this behavior).

The autoupdate-service remembers for every key what the last value was, that was sent to the client. It only sends a value to the client, if it is different then the last time.

As you wrote, the client gets first the response `"meeting/5/logo_$web_header_id": 97`
Then he gets some updates on the key `"meeting/5/logo_$_id": []` but no update on the key above.

Then the datastore tells the autoupdate-service, that the value of the key `meeting/5/logo_$web_header_id` to `97`.

The autoupdate-service sees, that your client has requested this key. But it also sees, that the last time this key was sent to your connection was with the value `97`. Since the value did not change, it does not send the value again.

One way to change this behavior would be, that if a key is not requested anymore, the autoupdate-server sends the value `null` for this key. So when the value is requested again, it "changes" from `null` to `97`. We tried this in #321 and had to revert it in #337 since it introduced other problems.

Another way would be, that if a key gets removed from a request the autoupdate-service does not send anything to the client, but clears the internal filter-cache. So when the key gets an update again, the value gets send again.

This could result in situations where a key with the same value are send twice to the client. But the only problem should be unnecessary traffic. If you think this would solve your problem, I could try implement it.

**Comment by GabrielInTheWorld** [comment]
Well, I think, it would be better, if the AU-service sends a key again even if it hasn't changed.

**Comment by ostcar** [comment]
> Well, I think, it would be better, if the AU-service sends a key again even if it hasn't changed.

You mean every time or only in this rare case? If I send it every time, it will be a lot of traffic.

**Comment by GabrielInTheWorld** [comment]
> > Well, I think, it would be better, if the AU-service sends a key again even if it hasn't changed.
> 
> You mean every time or only in this rare case? If I send it every time, it will be a lot of traffic.

At least in this rare case...
