### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-autoupdate-service#383]
The autoupdate service provides very little log output; most of the time it remains *completely* silent which is very disconcerting.

Considering that it is a central service that is handling a lot of connections, surely there is relevant information that could be logged.  I would like to see common logging facilities including log levels if possible.

**Comment by ostcar** [comment]
I can do this. You just have to tell me what information you need.

I don't want to add log levels. I like the idea from this article, that there should only be the log levels debug and info: https://dave.cheney.net/2015/11/05/lets-talk-about-logging

This your are the user of the service (in contrast of the developer) I will add all logs you think you need for running the service. I thought that you were only interested in internal errors since this is the only thing you have to respond to. But if you need more data, I don't have any problem adding then. Just tell me what data this is.

I don't think that log messages are the best (or only) thing to get observability.

I tried adding metric to the autoupdate service of os3 but removed then, as they were not used. I asked many times since the start of os4 that we instrument our services with [opentelemetry](https://opentelemetry.io/) but this was not important enough.

I propose, that you tell me the situations in which you want a log message, and I add them and then we take in January about metrics and traces.

**Comment by gsiv** [comment]
> I don't want to add log levels. I like the idea from this article, that there should only be the log levels debug and info: https://dave.cheney.net/2015/11/05/lets-talk-about-logging

That, clearly, differs from case to case and I'd wager that the author did not have networked services in mind.  It would be madness if, e.g., Apache or Postgres offered only two levels, for developers and "users".  I don't intend to blog about it though.  If we can get decent INFO level logging, I'll be more than happy.

> I thought that you were only interested in internal errors since this is the only thing you have to respond to.

I appreciate your line of thinking and the effort to avoid creating useless info; however, your assumption is incomplete.

A few examples off the top of my head: Sometimes the absence of expected logs is valuable information.  `404 page not found` responses are not internal errors, yet they would hint at important problems within the stack.  Slow processing times are a problem, especially for the autoupdate service, even if the processing is ultimately error-free.

To get started with logging, I would orient myself on comparable, widely-used software.  Not all software outside of the Go bubble does *everything* wrong. ;)

> I don't think that log messages are the best (or only) thing to get observability.

Sure, they may be neither but, arguably, they should *always* be available.  Unless you want to make some huge logging setup a de facto dependency of OpenSlides, of course.

> I tried adding metric to the autoupdate service of os3 but removed then, as they were not used.

That's because that was something entirely different.  For example, it could never tell us what the service was doing several hours or days ago, especially if it had been recreated in the meantime.

> I propose, that you tell me the situations in which you want a log message, and I add them and then we take in January about metrics and traces.

For starters, what I want the logging to tell us about the autoupdate service is:

  1. that it is doing anything at all
  2. what it is doing and when
  3. how long it took to do something

Additionally, I find regular aggregated timing information such as PgBouncer's quite helpful but maybe that's a slightly different issue.

**Comment by ostcar** [comment]
Maybe this topic is to complex to solve it in an issue like this.

What I need are concrete examples when to log what. "anything at all" is not concrete enough.

Your examples seems more like cases for traces instead of logs. They can tell you how long something took and if there are errors like 404.

I will prepare an demo for our meeting in January.

**Comment by gsiv** [comment]
> What I need are concrete examples when to log what. "anything at all" is not concrete enough.

I was hoping to give you an idea as to what *kind* of information logs should, IMO, convey.  Beyond that, it's difficult to specify things in detail that I don't know much about.  Ultimately, for the implementation, we'll need your expert knowledge to fill in the gaps.

Maybe some examples can illustrate my thinking a little more, though.  Since the autoupdate service speaks HTTP, maybe existing HTTP request logging formats could be used for inspiration.  The following is an exemplary line logged by HAProxy:

```
[23/Dec/2021:14:55:00.000] port_443~ port_443/openslides.example.com 0/0/4/18/1128219 200 379727 - - CD-- 1350/1350/260/186/0 0/0 {openslides.example.com|} "GET /system/autoupdate?change_id=182094900876 HTTP/1.1"
```

This includes, inter alia, a timestamp, the request, the return code, timers, and connection stats.  This is pretty good; maybe something similar would make sense for the autoupdate service?

Here is a very different, made-up example (which may very well be nonsensical or infeasible):

```
14:55:01.000 INFO: Received status update (change_id=182094900876) from client 1
14:55:01.001 INFO: Sent status update (change_id=182094900876) to client 1/10 [2 ms]
[...]
14:55:02.000 INFO: Sent status update (change_id=182094900876) to client 9/10 [10 ms]
14:55:02.001 INFO: Finished sending status update (change_id=182094900876) after 1000 ms
14:55:02.002 INFO: Received vote (change_id=12345) from client 1
14:55:02.003 INFO: Sent vote (change_id=12345) to client 1/10 [2 ms]
[...]
14:55:02.005 ERROR: Failed to sent vote (change_id=12345) to client 9/10
14:55:02.006 INFO: Finished sending vote (change_id=12345) after 1000 ms
```

Again, this is just roughly the sort of logging I would expect.  I can't tell you what *exactly* the autoupdate service should be logging or in which format, so I'm looking forward to your ideas.

**Comment by ostcar** [comment]
@peb-adr I added the metric logs. Do you think I can close this?
