### ISSUE TITLE
A user with `agenda.can_manage` and `mediafile.can_manage` cannot see mediafiles

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#409]
Login as a user in the group `staff` (who can manage agenda items and mediafiles). Go to a topic, edit it and try to attach some mediafiles.

**Comment by ostcar** [comment]
This is the current behavior (that I moved from the wiki): https://github.com/OpenSlides/openslides-autoupdate-service/blob/fc953dc21f91240ae0ff06ea9514e080bca1be32/internal/restrict/collection/mediafile.go#L11-L21

This could be outdated, since there is only the `mediafile.can_see`- Permission mentioned but not `mediafile.can_manage`. @FinnStutzenstein did probably define this rules before the `mediafile.can_manage` permission was created.

I think the solution is, that a new rule is created:
```
The user can see a mediafile, if any of:
   [...]
   The user has mediafile.can_manage
```

Is this correct?

**Comment by GabrielInTheWorld** [comment]
Well, the `mediafile.can_manage` permission inherits the permission `mediafile.can_see`. So, every user who has either the permission `mediafile.can_manage` or `mediafile.can_see` can see a mediafile.
If your approach satisfies this condition, then it is correct.
