### ISSUE TITLE
Users cannot see their own `committee_$can_manage_management_level`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#424]
I have a user, who can only manage one committee. After signing in as the user, I got only this response from the AU-service:
```js
{
    "committee_$_management_level": [
        "can_manage"
    ],
    "committee_$can_manage_management_level": null,
    "committee_ids": [
        2
    ],
    "default_number": "",
    "default_structure_level": "",
    "default_vote_weight": 1,
    "email": "",
    "first_name": "bla",
    "id": 5,
    "is_physical_person": true,
    "is_present_in_meeting_ids": null,
    "last_name": "",
    "title": "",
    "username": "bla"
}
```

This is the request, I sent:
```js
[
  {
    "ids": [5],
    "collection": "user",
    "fields": {
    "title": null,
    "first_name": null,
    "last_name": null,
    "pronoun": null,
    "username": null,
    "vote_weight_$": {
        "type": "template"
    },
    "structure_level_$": {
        "type": "template"
    },
    "number_$": {
        "type": "template"
    },
    "email": null,
    "gender": null,
    "is_active": null,
    "is_physical_person": null,
    "is_present_in_meeting_ids": null,
    "last_email_send": null,
    "default_number": null,
    "default_structure_level": null,
    "default_vote_weight": null,
    "comment_$": {
        "type": "template"
    },
    "committee_ids": null,
    "organization_management_level": null,
    "default_password": null,
    "committee_$_management_level": {
        "type": "template"
    },
    "id": null
    }
  }
]
```

**Comment by ostcar** [comment]
I understand the problem. Currently, this is the expected behaviour. The only difference is, that the value should not be `null` but an empty list.

The field `user/committee_$can_manage_management_level` is a `relation-list`-filed:  https://github.com/OpenSlides/openslides-backend/blob/ce45a16a366122bab7dd95a95e3ea27f1fc44b8a/global/meta/models.yml#L665

It relates to `committee/user_$_management_level`. That means, to see a value in the relation-list field, the user needs also the permission to see the related committee-field. `committee/user_$_management_level` has the restriction mode B: https://github.com/OpenSlides/openslides-backend/blob/ce45a16a366122bab7dd95a95e3ea27f1fc44b8a/global/meta/models.yml#L660

To see the restriction mode B of the committee-collection, the user needs to have the organization management level can_manage_organization or higher: https://github.com/OpenSlides/openslides-autoupdate-service/blob/a50ae687d25ae4cfefce51f794961773bec1d1e8/internal/restrict/collection/committee.go#L11-L17

One possible way to fix this is by changing the restriction mode from `B` to `A`. Then all committee members can see the user-ids the committee managers. I think this is the easiest fix and I don't think that it is a problem that they see it.

Another way is to create a new restriction mode `C` for the field `committee/user_$_management_level`. And define it, that a user can see it, when he has the OML can_manage_organization or is a committee manager.

Can you have a look at all the other fields with restriction mode `B`: https://github.com/OpenSlides/openslides-autoupdate-service/blob/a50ae687d25ae4cfefce51f794961773bec1d1e8/internal/restrict/field_def.go#L339-L342

Maybe the definition of the restriction mode `B` is wrong. Maybe the definition should be changed, that a committee manager can see all of these fields. @emanuelschuetze what do you think?

**Comment by ostcar** [comment]
Talked with Emanuel. We change the committee mode b
