### ISSUE TITLE
AU-service does not send a `null`-value on `block_id`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#444]
I sent this request to the AU-service:
```js
{
    "collection": "motion_block",
    "ids": [
        2
    ],
    "fields": {
        "title": null,
        "internal": null,
        "id": null,
        "motion_ids": {
            "type": "relation-list",
            "collection": "motion",
            "fields": {
                "sequential_number": null,
                "title": null,
                "number": null,
                "created": null,
                "block_id": null,
                "id": null,
                "state_id": {
                    "type": "relation",
                    "collection": "motion_state",
                    "fields": {
                        "name": null,
                        "css_class": null,
                        "next_state_ids": null,
                        "id": null
                    }
                },
                [...]
            }
        },
    [...]
    }
}
```

Now, I removed a motion from a `motion_block`, but I only get this response:
```js
{
    "motion_block/2/motion_ids": [
        8,
        9
    ]
}
```

The previous value was:
```js
{
    "motion_block/2/motion_ids": [
        7,
        8,
        9
    ]
}
```

As you can see, there is the update for the motion missing. Something like:
```
{
    "motion/7/block_id": null
}
```

**Comment by ostcar** [comment]
This is the problem we already talked about in other issues. The current behavior is expected. I can change it, when we find a good solution. My last PR on this topic had to be reversed, since it introduced more problems then it solved.

The problem is, that when an update happens, then the request get parsed again and it is generated a list from fqfields that are requested.

In your case motion/7 was removed. So after the update `motion_block/2/motion_ids` is `[8,9]`. The result is, that the fqfield `motion/7/block_id` is not requested anymore. Since it is not requested, I don't return the value.

Who would you like the autoupdate service to behave?

**Comment by GabrielInTheWorld** [comment]
> This is the problem we already talked about in other issues. The current behavior is expected. I can change it, when we find a good solution. My last PR on this topic had to be reversed, since it introduced more problems then it solved.
> 
> The problem is, that when an update happens, then the request get parsed again and it is generated a list from fqfields that are requested.
> 
> In your case motion/7 was removed. So after the update `motion_block/2/motion_ids` is `[8,9]`. The result is, that the fqfield `motion/7/block_id` is not requested anymore. Since it is not requested, I don't return the value.

I was afraid, that this is the problem... However, I thought, that at least in this case the value `motion/7/block_id: null` will be sent.

> 
> Who would you like the autoupdate service to behave?

Okay! If you are of the opinion, that it would bring us more problems implementing those `null`-values, than it solved, then I will workaround this issue.
