### ISSUE TITLE
Implement an option to request autoupdates for an entire collection

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-autoupdate-service#536]
Background:
The current subscription method of requesting the data concerning an array of ids works very well for meeting-internal lists (like the motion list), but it is a bit suboptimal for organization related lists, since the current practice requires that there is some form of parent object that holds a list with the actually desired set of data (which is not necessarily given for organization level lists that usually need to show an entire collection).
This is especially problematic for the account list, which currently does not receive autoupdates for newly created users, because we currently have no choice but to use a presenter to request all current user ids and subscribe to those.

That is why it would be good to have a method to request autoupdates for entire collections, this would not only simplify these types of requests quite a bit, it would also reduce the number of requests that the client needs to send, because (in the case of the account subscription) we would neither need to call that presenter, nor updare our autoupdate request upon every single new user that the client gets to know.

**Comment by ostcar** [comment]
This is not possible by design and would be very hard to solve with the current implementation from the autoupdate-service.

One reason is, that this kind of request would by very expensive. If you have 5.000 meetings and request the motion collection, then it would request thousands of collections.

The account list is the only case where we need this. This is the reason, this is the only presenter for a call like this. In all other cases, there is a relation_list-field that holds all needed ids. See here for example: 

https://github.com/OpenSlides/openslides-backend/blob/8b7cb1e6dd462d6cd173cc0f520832bed72b9359/global/meta/models.yml#L115-L149

I don't like to introduce this to general feature, just for this one use case. Is there another way to solve this?

**Comment by r-peschke** [comment]
https://github.com/OpenSlides/openslides-backend/issues/1439 will introduce fields organization.user_ids and user.organization_id. The autoupdate service can use this fields without any special handling

**Comment by ostcar** [comment]
@luisa-beerboom Can this be closed?

**Comment by luisa-beerboom** [comment]
Yes, I'll close it
