### ISSUE TITLE
[RTF] missing autoupdate for speaker list

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-autoupdate-service#714]
Speaker lists cannot be projected in the RTF-instance, it should be possible to project the speaker-list.

While in the projector-view the following error is thrown: 

![projector-speaker-list](https://github.com/OpenSlides/openslides-autoupdate-service/assets/69210919/daac1014-58a4-4132-b6fd-db2eb29933e5)

**Comment by ostcar** [comment]
Could you paste the full error message? Only the first part of it can be seen in you screenshot

**Comment by ostcar** [comment]
It should be fixed now in the branch. Could you confirm this and then close this issue?

I also found two other places in the projector, where I did not add the meeting_user. The problem is, that the projector-tests do not test against the models.yml, but against its own values. So there is no way to find all the places automatically. But I think, I got all places now

**Comment by Elblinator** [comment]
Jup, it's fixed now! 
thanks!
